import tkinter as tk
app = tk.Tk()

def showme():
    name = E1.get()
    A = E2.get()
    print(name)
    print(A)
app.geometry("500x500")
app.title('เขียนโดย อานัส')
l1 = tk.Label(text='ยินดีต้อนรับเข้าสู่ Python')
l2 = tk.Label(text='โดย กฤตพล รอบรู้')
l3 = tk.Label(text='กรอกชื่อสินค้า:')
E1 = tk.Entry()
l4 = tk.Label(text='ราคาสินค้า:')
E2 = tk.Entry()
B1 = tk.Button(text='ตกลง', command= showme)
#label.pack()
#label.grid(row=0, column=5)
l1.place(x=50, y=10)
l2.place(x=50, y=35)
l3.place(x=20, y=70)
E1.place(x=100, y=70)
l4.place(x=20, y=100)
E2.place(x=100, y=100)
B1.place(x=100, y=130)
